# @host = http://localhost:7071
@host = https://snapsecretfunctionappproduction.azurewebsites.net

###
# @name CreateSecret
POST {{host}}/api/v1/secrets
Content-Type: application/json

{
    "expireIn": "0.01:00:00.0000",
    "text": "MySuperSecretPassword"
}

###
@location = {{CreateSecret.response.headers.location}}

###
# @name SlackCreateSecret
POST {{host}}/api/v1/secrets-slack
Content-Type: application/x-www-form-urlencoded

text=MySuperSecretPassword

###
@location = {{SlackCreateSecret.response.body.text}}

###
POST {{location}}
