# @host = http://localhost:7071
@host = https://snapsecretfunctionappproduction.azurewebsites.net

###
# @name CreateSecret
POST {{host}}/api/v1/secrets
Content-Type: application/json

{
    "expireIn": "0.01:00:00.0000",
    "text": "MySuperSecretPassword"
}

###
@location = {{CreateSecret.response.headers.location}}

###
POST {{location}}
