name: Deploy
on:
  push:
    branches: [ 'main' ]
jobs:
  deploy:
    name: Production
    environment: Production
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.x
      - uses: actions/setup-dotnet@v1      
      - run: dotnet build -c Release
      - run: dotnet test --no-build --verbosity normal
      - uses: pulumi/actions@v3
        id: pulumi_up
        with:
          command: up
          stack-name: Production
          upsert: true
          refresh: true
          work-dir: ./infra/SnapSecret.Infrastructure.PulumiAzure
        env:
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
      - uses: pulumi/actions@v3
        if: ${{ steps.pulumi_up.outputs.NeedsRerun == 'true'}}
        id: pulumi_up_rerun
        with:
          command: up
          stack-name: Production
          upsert: true
          refresh: true
          work-dir: ./infra/SnapSecret.Infrastructure.PulumiAzure
        env:
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
