name: Preview
on:
  pull_request:
    paths:
        - 'infra/**'
jobs:
  preview:
    name: Preview
    environment: Production
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0'
      - run: dotnet build -c Release
      - run: dotnet test --no-build --verbosity normal
      - uses: pulumi/actions@v3
        with:
          command: preview
          stack-name: Production
          comment-on-pr: true
          upsert: true
          work-dir: ./infra/SnapSecret.Infrastructure.PulumiAzure
        env:
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}