name: Preview Infrastructure
on:
  - pull_request
jobs:
  preview:
    name: Preview
    environment: Production
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.x
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0'
          include-prerelease: true
      - run: dotnet build -c Release
      - uses: pulumi/actions@v3
        with:
          command: preview
          stack-name: Production
          comment-on-pr: true
          upsert: true
          work-dir: ./src/SnapSecret.Infrastructure.PulumiAzure
        env:
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}